### ISSUE TITLE
false positive?

### ISSUE THREAD

**Issue by AskAlice** [k8s-at-home/sops-pre-commit#24]
Check for unencrypted Kubernetes secrets in manifests.......................Failed
- hook id: forbid-secrets
- exit code: 1

Unencrypted Kubernetes secret detected in file: tmpl/cluster/cluster-secrets.sops.yaml
```
# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ${BOOTSTRAP_CLOUDFLARE_DOMAIN}
    SECRET_CLOUDFLARE_EMAIL: ${BOOTSTRAP_CLOUDFLARE_EMAIL}
    SECRET_PILOT_TOKEN: ${BOOTSTRAP_TRAEFIK_PILOT_TOKEN}
```
git diff 
![image](https://user-images.githubusercontent.com/1855905/186546007-dd7a7df6-30e0-443a-982a-d9ac76fcef53.png)

**Comment by onedr0p** [comment]
Unfortunately there's no great way to detect what secrets _should_ be encrypted if not already. It would be to be either the filename (e.g. `something.sops.yaml`) or the way this checks is by checking the file content for `^kind:\ssecret$` AND contains `ENC.AES256`.

The work around is to make sure your files are encrypted and use the `--no-verify` flag on `git commit`

**Comment by almereyda** [comment]
Here we could reuse the values of the `path_regex` keys within the items of the `creation_rules` array in `.sops.yaml` (at a repository's root) to distinctively identify the files that are required to be encrypted.

**Comment by tuxpeople** [comment]
I do have another false positive, which I was able to commit using @onedr0p's `--no-verify` hint:

```yaml
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: kube-vip
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: kube-vip
---
[...]
```

Well, from the perspective of the check, it's not really a false positive. It is a `Secret` and it isn't encrypted. But from de DevOps perspective, it's a false positive because there is no unencrypted data in it.

May I suggest to either check if there is `data` or `stringData` specify (would solve my issue) or add a disable-comment like for xamllint in above screenshot? That would solve my and @AskAlice's issue.
