### ISSUE TITLE
Exclude SecretProviderClass from secret CSI

### ISSUE THREAD

**Issue by Vikaspogu** [k8s-at-home/sops-pre-commit#26]
Would it be possible to exclude `kind: SecretProviderClass` and update regex only to match `Kind: Secret` ?

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
...
```
