### ISSUE TITLE
Executable not found

### ISSUE THREAD

**Issue by BeeHiveJava** [k8s-at-home/sops-pre-commit#7]
Running sops-pre-commit gives me the following error:

```
Check for unencrypted Kubernetes secrets in manifests.......................Failed
- hook id: forbid-secrets
- exit code: 1

Executable `forbid_secrets` not found
```

This happens when I run it as a commit-hook as well as with using `pre-commit run --all-files`. My configuration is as follows:
```yaml
- repo: https://github.com/k8s-at-home/sops-pre-commit
  rev: v2.0.3
  hooks:
    - id: forbid-secrets
      stages:
        - commit
```

Interesting to know is that I'm running this on windows in WSL (Ubuntu 20-04) in a devcontainer (VSCode). I'm not sure what's wrong, I'll try to look into it myself as well but maybe you guys have any ideas?

**Comment by onedr0p** [comment]
Have you tried running this outside the devcontainer?

**Comment by anthr76** [comment]
@BeeHiveJava Do you have your full .pre-commit.yaml file handy? Interested to see if you have other hooks that use python. Perhaps the devcontainer is missing  python dependencies and failing silently.

**Comment by BeeHiveJava** [comment]
@anthr76 of course! editorconfig-checker and yamllint are python hooks, commitlint is a node hook.

```yaml
---
repos:
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.3.5
    hooks:
      - id: editorconfig-checker
        stages:
          - commit
        args: [--config=.ecrc]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.1
    hooks:
      - id: yamllint
        stages:
          - commit
        args: [--config-file=.yamllint.yaml]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
     rev: v4.1.0
     hooks:
       - id: commitlint
         stages:
           - commit-msg
         args: [--config=.commitlintrc.yaml]
         additional_dependencies:
           - "@commitlint/config-conventional"
           
  - repo: https://github.com/k8s-at-home/sops-pre-commit
    rev: v2.0.3
    hooks:
      - id: forbid-secrets
        stages:
          - commit
```
